// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoodleFacts.Models;

namespace RileyBot.Migrations
{
    [DbContext(typeof(RileyContext))]
    partial class RileyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("NoodleFacts.Models.Fact", b =>
                {
                    b.Property<int>("FactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FactText")
                        .HasColumnType("TEXT");

                    b.HasKey("FactID");

                    b.ToTable("Facts");
                });
#pragma warning restore 612, 618
        }
    }
}
